In [16]:
import numpy as np
import pandas as pd
import polars as pl
import sys
import re
import os
import matplotlib.pyplot as plt
import seaborn as sns
import plotly
import plotly.express as px


pd.set_option('display.max_columns',None)
import psycopg2


#to scale the data using z-score 
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

#Algorithms to use
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier

#Metrics to evaluate the model
from sklearn.metrics import confusion_matrix, classification_report, precision_recall_curve

import warnings
warnings.filterwarnings("ignore")

#importing PCA and TSNE
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE

In [9]:
df = pd.read_csv(r'C:/Users/GenepoweRx_Madhu/Downloads/S04380110_Covered_Extd.bed', sep = '\t', header = None, error_bad_lines=False)
df.columns = ['CHROM', 'Start_pos', 'End_pos', 'start', 'end']
dataset1 = df.drop(0)
# If you want to reset the index after dropping rows
dataset1.reset_index(drop=True, inplace=True)
dataset1 = dataset1[['CHROM', 'start', 'end']]
dataset1.to_csv(r'C:/Users/GenepoweRx_Madhu/Downloads/srinivas_sir_covered.bed', header=None, sep='\t', index=False)

In [13]:
import os

def read_bed_file(bed_file):
    bed_positions = set()
    with open(bed_file, 'r') as f:
        for line in f:
            fields = line.strip().split('\t')
            if len(fields) >= 3:
                chrom = fields[0]
                try:
                    start = int(fields[1])
                    end = int(fields[2])
                except ValueError:
                    continue  # Skip this line if start or end position is not an integer
                for pos in range(start, end + 1):
                    bed_positions.add((chrom, pos))
    return bed_positions

def normalize_chrom_name(chrom):
    return chrom.split('_')[0]

def filter_tsv_file(tsv_file, bed_positions):
    filtered_tsv_records = []
    with open(tsv_file, 'r') as f:
        for line in f:
            fields = line.strip().split('\t')
            if len(fields) >= 2:
                raw_chrom = fields[0]
                chrom = normalize_chrom_name(raw_chrom)
                try:
                    pos = int(fields[1])
                except ValueError:
                    continue  # Skip this line if 'POS' is not an integer
                if (chrom, pos) in bed_positions:
                    filtered_tsv_records.append(line)
    return filtered_tsv_records

def write_filtered_tsv(filtered_tsv_records, output_file):
    with open(output_file, 'w') as f:
        for record in filtered_tsv_records:
            f.write(record)

def main():
    bed_file = r'C:/Users/GenepoweRx_Madhu/Downloads/Depth_files/srinivas_sir_covered.bed'
    input_folder = r'C:/Users/GenepoweRx_Madhu/Downloads/Depth_files/'
    output_folder = r'C:/Users/GenepoweRx_Madhu/Downloads/Depth_files/COVERED_TSV/'

    bed_positions = read_bed_file(bed_file)

    if not os.path.exists(output_folder):
        os.makedirs(output_folder)

    for filename in os.listdir(input_folder):
        if filename.endswith('.tsv'):
            input_file = os.path.join(input_folder, filename)
            output_file = os.path.join(output_folder, filename)
            filtered_tsv_records = filter_tsv_file(input_file, bed_positions)
            write_filtered_tsv(filtered_tsv_records, output_file)

if __name__ == "__main__":
    main()

In [14]:
import os

def read_bed_file(bed_file):
    bed_positions = set()
    with open(bed_file, 'r') as f:
        for line in f:
            fields = line.strip().split('\t')
            if len(fields) >= 3:
                try:
                    chrom = fields[0]
                    start = int(fields[1])
                    end = int(fields[2])
                except ValueError:
                    continue  # Skip this line if start or end position is not an integer
                for pos in range(start, end + 1):
                    bed_positions.add((chrom, pos))
    return bed_positions

def filter_tsv_file(tsv_file, bed_positions):
    filtered_tsv_records = []
    with open(tsv_file, 'r') as f:
        for line in f:
            fields = line.strip().split('\t')
            if len(fields) >= 2:
                try:
                    chrom = fields[0]
                    pos = int(fields[1])
                except ValueError:
                    continue  # Skip this line if 'POS' is not an integer
                if (chrom, pos) in bed_positions:
                    filtered_tsv_records.append(line)
    return filtered_tsv_records

def write_filtered_tsv(filtered_tsv_records, output_file):
    with open(output_file, 'w') as f:
        for record in filtered_tsv_records:
            f.write(record)

def main():
    bed_file = r'C:/Users/GenepoweRx_Madhu/Downloads/Depth_files/srinivas_sir_covered.bed'
    input_folder = r'C:/Users/GenepoweRx_Madhu/Downloads/Depth_files/'
    output_folder = r'C:/Users/GenepoweRx_Madhu/Downloads/Depth_files/COVERED_TSV/Covered_new/'

    bed_positions = read_bed_file(bed_file)

    if not os.path.exists(output_folder):
        os.makedirs(output_folder)

    for filename in os.listdir(input_folder):
        if filename.endswith('.tsv'):
            input_file = os.path.join(input_folder, filename)
            output_file = os.path.join(output_folder, filename)
            filtered_tsv_records = filter_tsv_file(input_file, bed_positions)
            write_filtered_tsv(filtered_tsv_records, output_file)

if __name__ == "__main__":
    main()

In [15]:
import os

def read_bed_file(bed_file):
    bed_positions = set()
    with open(bed_file, 'r') as f:
        for line in f:
            fields = line.strip().split('\t')
            if len(fields) >= 3:
                try:
                    chrom = fields[0]
                    start = int(fields[1])
                    end = int(fields[2])
                except ValueError:
                    continue  # Skip this line if start or end position is not an integer
                for pos in range(start, end + 1):
                    bed_positions.add((chrom, pos))
    return bed_positions

def filter_tsv_file(tsv_file, bed_positions):
    filtered_tsv_records = []
    with open(tsv_file, 'r') as f:
        for line in f:
            fields = line.strip().split('\t')
            if len(fields) >= 2:
                try:
                    chrom = fields[0]
                    pos = int(fields[1])
                except ValueError:
                    continue  # Skip this line if 'POS' is not an integer
                if (chrom, pos) in bed_positions:
                    filtered_tsv_records.append(line)
    return filtered_tsv_records

def write_filtered_tsv(filtered_tsv_records, output_file, column_headers):
    with open(output_file, 'w') as f:
        f.write('\t'.join(column_headers) + '\n')
        for record in filtered_tsv_records:
            f.write(record)

def main():
    bed_file = r'C:/Users/GenepoweRx_Madhu/Downloads/Depth_files/srinivas_sir_covered.bed'
    input_folder = r'C:/Users/GenepoweRx_Madhu/Downloads/Depth_files/'
    output_folder = r'C:/Users/GenepoweRx_Madhu/Downloads/Depth_files/COVERED_TSV/Covered_new/'

    bed_positions = read_bed_file(bed_file)

    if not os.path.exists(output_folder):
        os.makedirs(output_folder)

    for filename in os.listdir(input_folder):
        if filename.endswith('.tsv'):
            input_file = os.path.join(input_folder, filename)
            output_file = os.path.join(output_folder, filename)
            with open(input_file, 'r') as f:
                column_headers = f.readline().strip().split('\t')
            filtered_tsv_records = filter_tsv_file(input_file, bed_positions)
            write_filtered_tsv(filtered_tsv_records, output_file, column_headers)

if __name__ == "__main__":
    main()

In [24]:
df = pd.read_excel(r'C:/Users/GenepoweRx_Madhu/Downloads/Allele_definitions_CPIC.xlsx')
df

,id,version,genesymbol,name,pharmvarid,matchesreferencesequence,structuralvariation,allele_location_value
0,1508724,38,ABCG2,rs2231142 reference (G),NaN,True,False,"alleledefinitionid': 1508724, 'locationid': 15..."
1,1508726,38,ABCG2,rs2231142 variant (T),NaN,False,False,"alleledefinitionid': 1508726, 'locationid': 15..."
2,777262,57,CACNA1S,Reference,NaN,True,False,"alleledefinitionid': 777262, 'locationid': 777..."
3,777264,57,CACNA1S,c.520C>T,NaN,False,False,"alleledefinitionid': 777264, 'locationid': 777..."
4,777266,57,CACNA1S,c.3257G>A,NaN,False,False,"alleledefinitionid': 777266, 'locationid': 777..."
...,...,...,...,...,...,...,...,...
866,779502,57,UGT1A1,*80+*28,NaN,False,False,"alleledefinitionid': 779502, 'locationid': 779..."
867,779504,57,UGT1A1,*80+*37,NaN,False,False,"alleledefinitionid': 779504, 'locationid': 779..."
868,779492,57,UGT1A1,*27,NaN,False,False,"alleledefinitionid': 779492, 'locationid': 779..."
869,779509,57,VKORC1,rs9923231 variant (T),NaN,False,False,"alleledefinitionid': 779509, 'locationid': 779..."
870,779507,57,VKORC1,rs9923231 reference (C),NaN,True,False,"alleledefinitionid': 779507, 'locationid': 779..."

In [25]:
df['Allele_location_value'] = df['allele_location_value'].str.split('^')
df = df.explode('Allele_location_value')
df

,id,version,genesymbol,name,pharmvarid,matchesreferencesequence,structuralvariation,allele_location_value,Allele_location_value
0,1508724,38,ABCG2,rs2231142 reference (G),NaN,True,False,"alleledefinitionid': 1508724, 'locationid': 15...","alleledefinitionid': 1508724, 'locationid': 15..."
1,1508726,38,ABCG2,rs2231142 variant (T),NaN,False,False,"alleledefinitionid': 1508726, 'locationid': 15...","alleledefinitionid': 1508726, 'locationid': 15..."
2,777262,57,CACNA1S,Reference,NaN,True,False,"alleledefinitionid': 777262, 'locationid': 777...","alleledefinitionid': 777262, 'locationid': 777..."
2,777262,57,CACNA1S,Reference,NaN,True,False,"alleledefinitionid': 777262, 'locationid': 777...","'alleledefinitionid': 777262, 'locationid': 7..."
3,777264,57,CACNA1S,c.520C>T,NaN,False,False,"alleledefinitionid': 777264, 'locationid': 777...","alleledefinitionid': 777264, 'locationid': 777..."
...,...,...,...,...,...,...,...,...,...
867,779504,57,UGT1A1,*80+*37,NaN,False,False,"alleledefinitionid': 779504, 'locationid': 779...","alleledefinitionid': 779504, 'locationid': 779..."
867,779504,57,UGT1A1,*80+*37,NaN,False,False,"alleledefinitionid': 779504, 'locationid': 779...","'alleledefinitionid': 779504, 'locationid': 1..."
868,779492,57,UGT1A1,*27,NaN,False,False,"alleledefinitionid': 779492, 'locationid': 779...","alleledefinitionid': 779492, 'locationid': 779..."
869,779509,57,VKORC1,rs9923231 variant (T),NaN,False,False,"alleledefinitionid': 779509, 'locationid': 779...","alleledefinitionid': 779509, 'locationid': 779..."
870,779507,57,VKORC1,rs9923231 reference (C),NaN,True,False,"alleledefinitionid': 779507, 'locationid': 779...","alleledefinitionid': 779507, 'locationid': 779..."

In [26]:
df.to_excel(r'C:/Users/GenepoweRx_Madhu/Downloads/new_Allele_definitions_CPIC.xlsx')

In [89]:
df = pd.read_excel(r'C:/Users/GenepoweRx_Madhu/Downloads/new_Allele_definitions_CPIC.xlsx')
df

,id,version,genesymbol,name,pharmvarid,matchesreferencesequence,structuralvariation,Allele_location_value
0,1508724,38,ABCG2,rs2231142 reference (G),NaN,True,False,"alleledefinitionID: 1508724, locationID: 15087..."
1,1508726,38,ABCG2,rs2231142 variant (T),NaN,False,False,"alleledefinitionID: 1508726, locationID: 15087..."
2,777262,57,CACNA1S,Reference,NaN,True,False,"alleledefinitionID: 777262, locationID: 777260..."
3,777262,57,CACNA1S,Reference,NaN,True,False,"alleledefinitionID: 777262, locationID: 777261..."
4,777264,57,CACNA1S,c.520C>T,NaN,False,False,"alleledefinitionID: 777264, locationID: 777260..."
...,...,...,...,...,...,...,...,...
2030,779504,57,UGT1A1,*80+*37,NaN,False,False,"alleledefinitionID: 779504, locationID: 779484..."
2031,779504,57,UGT1A1,*80+*37,NaN,False,False,"alleledefinitionID: 779504, locationID: 10005..."
2032,779492,57,UGT1A1,*27,NaN,False,False,"alleledefinitionID: 779492, locationID: 779487..."
2033,779509,57,VKORC1,rs9923231 variant (T),NaN,False,False,"alleledefinitionID: 779509, locationID: 779506..."
2034,779507,57,VKORC1,rs9923231 reference (C),NaN,True,False,"alleledefinitionID: 779507, locationID: 779506..."

In [90]:
df['alleledefinitionID'] = df['Allele_location_value'].str.split(',').str[0].str.replace('alleledefinitionID:', '').str.strip()
df['locationID'] = df['Allele_location_value'].str.split(',').str[1].str.replace('locationID:', '').str.strip()
df['variantallele'] = df['Allele_location_value'].str.split(',').str[2].str.replace('variantallele:', '').str.strip()
df['Version'] = df['Allele_location_value'].str.split(',').str[3].str.replace('version:', '').str.strip()
df['ID'] = df['Allele_location_value'].str.split(',').str[4].str.replace('ID:', '').str.strip()
df['Version_sequence_location'] = df['Allele_location_value'].str.split(',').str[5].str.replace('version:', '').str.strip()
df['Name'] = df['Allele_location_value'].str.split(',').str[6].str.replace('name:', '').str.strip()
df['chromosomelocation'] = df['Allele_location_value'].str.split(',').str[7].str.replace('chromosomelocation:', '').str.strip()
df['genelocation'] = df['Allele_location_value'].str.split(',').str[8].str.replace('genelocation:', '').str.strip()
df['proteinlocation'] = df['Allele_location_value'].str.split(',').str[9].str.replace('proteinlocation:', '').str.strip()
df['Genesymbol'] = df['Allele_location_value'].str.split(',').str[10].str.replace('genesymbol:', '').str.strip()
df['dbsnpID'] = df['Allele_location_value'].str.split(',').str[11].str.replace('dbsnpID:', '').str.strip()
df['position'] = df['Allele_location_value'].str.split(',').str[12].str.replace('position:', '').str.strip()
df

,id,version,genesymbol,name,pharmvarid,matchesreferencesequence,structuralvariation,Allele_location_value,alleledefinitionID,locationID,variantallele,Version,ID,Version_sequence_location,Name,chromosomelocation,genelocation,proteinlocation,Genesymbol,dbsnpID,position
0,1508724,38,ABCG2,rs2231142 reference (G),NaN,True,False,"alleledefinitionID: 1508724, locationID: 15087...",1508724,1508723,G,1,1508723,38,421C>A,g.88131171G>T,g.105152C>A,Q141K,ABCG2,rs2231142,88131171
1,1508726,38,ABCG2,rs2231142 variant (T),NaN,False,False,"alleledefinitionID: 1508726, locationID: 15087...",1508726,1508723,T,1,1508723,38,421C>A,g.88131171G>T,g.105152C>A,Q141K,ABCG2,rs2231142,88131171
2,777262,57,CACNA1S,Reference,NaN,True,False,"alleledefinitionID: 777262, locationID: 777260...",777262,777260,G,1,777260,58,c.520C>T,g.201091993G>A,g.25574C>T,p.R174W,CACNA1S,rs772226819,201091993
3,777262,57,CACNA1S,Reference,NaN,True,False,"alleledefinitionID: 777262, locationID: 777261...",777262,777261,C,1,777261,58,c.3257G>A,g.201060815C>T,g.56752G>A,p.R1086H,CACNA1S,rs1800559,201060815
4,777264,57,CACNA1S,c.520C>T,NaN,False,False,"alleledefinitionID: 777264, locationID: 777260...",777264,777260,A,1,777260,58,c.520C>T,g.201091993G>A,g.25574C>T,p.R174W,CACNA1S,rs772226819,201091993
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2030,779504,57,UGT1A1,*80+*37,NaN,False,False,"alleledefinitionID: 779504, locationID: 779484...",779504,779484,T,1,779484,58,-364C>T,g.233759924C>T,g.175181C>T,5 Flanking,UGT1A1,rs887829,233759924
2031,779504,57,UGT1A1,*80+*37,NaN,False,False,"alleledefinitionID: 779504, locationID: 10005...",779504,1000510,TA(9),1,1000510,49,CA(TA)5TAA CA(TA)6TAA CA(TA)7TAA CA(TA)8TAA,g.233760235TA[6]; g.233760235TA[7]; g.23376023...,g.175492TA[6]; g.175492TA[7]; g.175492TA[8]; g...,5 Flanking,UGT1A1,rs3064744,233760235
2032,779492,57,UGT1A1,*27,NaN,False,False,"alleledefinitionID: 779492, locationID: 779487...",779492,779487,A,1,779487,58,686C>A,g.233760973C>A,g.176230C>A,p.P229Q,UGT1A1,rs35350960,233760973
2033,779509,57,VKORC1,rs9923231 variant (T),NaN,False,False,"alleledefinitionID: 779509, locationID: 779506...",779509,779506,T,1,779506,58,-1639G>A,g.31096368C>T,g.3588G>A,5 region,VKORC1,rs9923231,31096368
2034,779507,57,VKORC1,rs9923231 reference (C),NaN,True,False,"alleledefinitionID: 779507, locationID: 779506...",779507,779506,C,1,779506,58,-1639G>A,g.31096368C>T,g.3588G>A,5 region,VKORC1,rs9923231,31096368

In [94]:
grp1 = df.groupby(['id']).agg({'alleledefinitionID': lambda x: ','.join(str(i) for i in x),
                               'locationID': lambda x: ','.join(str(i) for i in x),
                               'variantallele': lambda x: ','.join(str(i) for i in x),
                               'Version': lambda x: ','.join(str(i) for i in x),
                               'ID': lambda x: ','.join(str(i) for i in x),
                               'Version_sequence_location': lambda x: ','.join(str(i) for i in x),
                               'Name': lambda x: ','.join(str(i) for i in x),
                               'chromosomelocation': lambda x: ','.join(str(i) for i in x),
                               'genelocation': lambda x: ','.join(str(i) for i in x),
                               'proteinlocation': lambda x: ','.join(str(i) for i in x),
                               'Genesymbol': lambda x: ','.join(str(i) for i in x),
                               'dbsnpID': lambda x: ','.join(str(i) for i in x),
                               'position': lambda x: ','.join(str(i) for i in x)}).reset_index()
grp1

,id,alleledefinitionID,locationID,variantallele,Version,ID,Version_sequence_location,Name,chromosomelocation,genelocation,proteinlocation,Genesymbol,dbsnpID,position
0,9000,[],nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
1,9001,[],nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
2,9002,[],nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
3,9003,[],nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
4,777262,"777262,777262","777260,777261","G,C","1,1","777260,777261","58,58","c.520C>T,c.3257G>A","g.201091993G>A,g.201060815C>T","g.25574C>T,g.56752G>A","p.R174W,p.R1086H","CACNA1S,CACNA1S","rs772226819,rs1800559","201091993,201060815"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
866,3318593,3318593,3318564,T,1,3318564,2,5071G>A,g.15892541C>T,g.10534G>A,p.E129L,CYP4F2,rs145875499,15892541
867,3318595,3318595,3318566,A,1,3318566,2,7941G>T,g.15889671C>A,g.13404G>T,p.A224S,CYP4F2,rs144233412,15889671
868,3318597,3318597,3318567,C,1,3318567,2,11594C>G,g.15886018G>C,g.17057C>G,p.L341V,CYP4F2,rs145174239,15886018
869,3318599,3318599,3318569,T,1,3318569,2,18200G>A,g.15879412C>T,g.23663G>A,p.R444H,CYP4F2,rs138971789,15879412
870,3318601,[],nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan

In [95]:
dt = pd.read_excel(r'C:/Users/GenepoweRx_Madhu/Downloads/dt_red.xlsx')
dt

          id
0    1508724
1    1508726
2     777262
3     777264
4     777266
..       ...
866   779502
867   779504
868   779492
869   779509
870   779507

[871 rows x 1 columns]

In [96]:
# Merge the datasets on the 'id' column and reorder dataset1 based on dataset2's order
result = dt.merge(grp1, on='id', suffixes=('dt', 'grp1'))

# Reorder the columns to match the original order
result = result[grp1.columns]
result

,id,alleledefinitionID,locationID,variantallele,Version,ID,Version_sequence_location,Name,chromosomelocation,genelocation,proteinlocation,Genesymbol,dbsnpID,position
0,1508724,1508724,1508723,G,1,1508723,38,421C>A,g.88131171G>T,g.105152C>A,Q141K,ABCG2,rs2231142,88131171
1,1508726,1508726,1508723,T,1,1508723,38,421C>A,g.88131171G>T,g.105152C>A,Q141K,ABCG2,rs2231142,88131171
2,777262,"777262,777262","777260,777261","G,C","1,1","777260,777261","58,58","c.520C>T,c.3257G>A","g.201091993G>A,g.201060815C>T","g.25574C>T,g.56752G>A","p.R174W,p.R1086H","CACNA1S,CACNA1S","rs772226819,rs1800559","201091993,201060815"
3,777264,777264,777260,A,1,777260,58,c.520C>T,g.201091993G>A,g.25574C>T,p.R174W,CACNA1S,rs772226819,201091993
4,777266,777266,777261,T,1,777261,58,c.3257G>A,g.201060815C>T,g.56752G>A,p.R1086H,CACNA1S,rs1800559,201060815
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
866,779502,"779502,779502","779484,1000510","T,TA(8)","1,1","779484,1000510","58,49","-364C>T,CA(TA)5TAA CA(TA)6TAA CA(TA)7TAA CA(TA...","g.233759924C>T,g.233760235TA[6]; g.233760235TA...","g.175181C>T,g.175492TA[6]; g.175492TA[7]; g.17...","5 Flanking,5 Flanking","UGT1A1,UGT1A1","rs887829,rs3064744","233759924,233760235"
867,779504,"779504,779504","779484,1000510","T,TA(9)","1,1","779484,1000510","58,49","-364C>T,CA(TA)5TAA CA(TA)6TAA CA(TA)7TAA CA(TA...","g.233759924C>T,g.233760235TA[6]; g.233760235TA...","g.175181C>T,g.175492TA[6]; g.175492TA[7]; g.17...","5 Flanking,5 Flanking","UGT1A1,UGT1A1","rs887829,rs3064744","233759924,233760235"
868,779492,779492,779487,A,1,779487,58,686C>A,g.233760973C>A,g.176230C>A,p.P229Q,UGT1A1,rs35350960,233760973
869,779509,779509,779506,T,1,779506,58,-1639G>A,g.31096368C>T,g.3588G>A,5 region,VKORC1,rs9923231,31096368
870,779507,779507,779506,C,1,779506,58,-1639G>A,g.31096368C>T,g.3588G>A,5 region,VKORC1,rs9923231,31096368

In [97]:
result.to_excel(r'C:/Users/GenepoweRx_Madhu/Downloads/new.xlsx', index=False)

In [64]:
# Extract values using regular expressions
df['alleledefinitionID'] = df['Allele_location_value'].str.extract(r'alleledefinitionID:\s*(\d+)', flags=re.IGNORECASE)
df['locationID'] = df['Allele_location_value'].str.extract(r'locationID:\s*(\d+)', flags=re.IGNORECASE)
df['variantallele'] = df['Allele_location_value'].str.extract(r'variantallele:\s*([A-Z])')
df['Version'] = df['Allele_location_value'].str.extract(r'version:\s*(\d+)', flags=re.IGNORECASE)
df['ID'] = df['Allele_location_value'].str.extract(r'ID:\s*(\d+)', flags=re.IGNORECASE)  # Adjusted regex for 'ID'
df['Name'] = df['Allele_location_value'].str.extract(r'name:\s*([^\s,]+)')
df['chromosomelocation'] = df['Allele_location_value'].str.extract(r'chromosomelocation:\s*([^\s,]+)')
df['genelocation'] = df['Allele_location_value'].str.extract(r'genelocation:\s*([^\s,]+)')
df['proteinlocation'] = df['Allele_location_value'].str.extract(r'proteinlocation:\s*([^\s,]+)')
df['Genesymbol'] = df['Allele_location_value'].str.extract(r'genesymbol:\s*([^\s,]+)')
df['dbsnpID'] = df['Allele_location_value'].str.extract(r'dbsnpID:\s*([^\s,]+)')
df['position'] = df['Allele_location_value'].str.extract(r'position:\s*(\d+)')
df

,id,version,genesymbol,name,pharmvarid,matchesreferencesequence,structuralvariation,Allele_location_value,alleledefinitionID,locationID,variantallele,Version,ID,Name,chromosomelocation,genelocation,proteinlocation,Genesymbol,dbsnpID,position
0,1508724,38,ABCG2,rs2231142 reference (G),NaN,True,False,"alleledefinitionID: 1508724, locationID: 15087...",1508724,1508723,G,1,1508724,421C>A,g.88131171G>T,g.105152C>A,Q141K,ABCG2,rs2231142,88131171
1,1508726,38,ABCG2,rs2231142 variant (T),NaN,False,False,"alleledefinitionID: 1508726, locationID: 15087...",1508726,1508723,T,1,1508726,421C>A,g.88131171G>T,g.105152C>A,Q141K,ABCG2,rs2231142,88131171
2,777262,57,CACNA1S,Reference,NaN,True,False,"alleledefinitionID: 777262, locationID: 777260...",777262,777260,G,1,777262,c.520C>T,g.201091993G>A,g.25574C>T,p.R174W,CACNA1S,rs772226819,201091993
3,777262,57,CACNA1S,Reference,NaN,True,False,"alleledefinitionID: 777262, locationID: 777261...",777262,777261,C,1,777262,c.3257G>A,g.201060815C>T,g.56752G>A,p.R1086H,CACNA1S,rs1800559,201060815
4,777264,57,CACNA1S,c.520C>T,NaN,False,False,"alleledefinitionID: 777264, locationID: 777260...",777264,777260,A,1,777264,c.520C>T,g.201091993G>A,g.25574C>T,p.R174W,CACNA1S,rs772226819,201091993
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2030,779504,57,UGT1A1,*80+*37,NaN,False,False,"alleledefinitionID: 779504, locationID: 779484...",779504,779484,T,1,779504,-364C>T,g.233759924C>T,g.175181C>T,"""5",UGT1A1,rs887829,233759924
2031,779504,57,UGT1A1,*80+*37,NaN,False,False,"alleledefinitionID: 779504, locationID: 10005...",779504,1000510,T,1,779504,CA(TA)5TAA,g.233760235TA[6];,g.175492TA[6];,"""5",UGT1A1,rs3064744,233760235
2032,779492,57,UGT1A1,*27,NaN,False,False,"alleledefinitionID: 779492, locationID: 779487...",779492,779487,A,1,779492,686C>A,g.233760973C>A,g.176230C>A,p.P229Q,UGT1A1,rs35350960,233760973
2033,779509,57,VKORC1,rs9923231 variant (T),NaN,False,False,"alleledefinitionID: 779509, locationID: 779506...",779509,779506,T,1,779509,-1639G>A,g.31096368C>T,g.3588G>A,"""5",VKORC1,rs9923231,31096368
2034,779507,57,VKORC1,rs9923231 reference (C),NaN,True,False,"alleledefinitionID: 779507, locationID: 779506...",779507,779506,C,1,779507,-1639G>A,g.31096368C>T,g.3588G>A,"""5",VKORC1,rs9923231,31096368

In [20]:
# Parse the strings in allele_location_value column into dictionaries
df['allele_location_value'] = df['allele_location_value'].apply(json.loads)

# Define a function to flatten nested dictionaries
def flatten_dict(d, prefix=''):
    flat_dict = {}
    for key, value in d.items():
        if isinstance(value, dict):
            flat_dict.update(flatten_dict(value, prefix + key + '_'))
        else:
            flat_dict[prefix + key] = value
    return flat_dict

# Apply the flatten_dict function to allele_location_value column
flattened_data = df['allele_location_value'].apply(flatten_dict)

# Convert the flattened_data into a DataFrame
flattened_df = pd.DataFrame(list(flattened_data))

# Concatenate the original DataFrame with the flattened DataFrame
result_df = pd.concat([df, flattened_df], axis=1)

# Drop the original allele_location_value column
result_df = result_df.drop('allele_location_value', axis=1)

# Display the resulting DataFrame
result_df

JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 3 (char 2)

In [3]:
df.allele_location_value.iloc[0]

"[{'alleledefinitionid': 1508724, 'locationid': 1508723, 'variantallele': 'G', 'version': 1, 'sequence_location': {'id': 1508723, 'version': 38, 'name': '421C>A', 'chromosomelocation': 'g.88131171G>T', 'genelocation': 'g.105152C>A', 'proteinlocation': 'Q141K', 'genesymbol': 'ABCG2', 'dbsnpid': 'rs2231142', 'position': 88131171}}]"

In [4]:
df.allele_location_value.iloc[1]

"[{'alleledefinitionid': 1508726, 'locationid': 1508723, 'variantallele': 'T', 'version': 1, 'sequence_location': {'id': 1508723, 'version': 38, 'name': '421C>A', 'chromosomelocation': 'g.88131171G>T', 'genelocation': 'g.105152C>A', 'proteinlocation': 'Q141K', 'genesymbol': 'ABCG2', 'dbsnpid': 'rs2231142', 'position': 88131171}}]"

In [5]:
df.allele_location_value.iloc[2]

"[{'alleledefinitionid': 777262, 'locationid': 777260, 'variantallele': 'G', 'version': 1, 'sequence_location': {'id': 777260, 'version': 58, 'name': 'c.520C>T', 'chromosomelocation': 'g.201091993G>A', 'genelocation': 'g.25574C>T', 'proteinlocation': 'p.R174W', 'genesymbol': 'CACNA1S', 'dbsnpid': 'rs772226819', 'position': 201091993}}, {'alleledefinitionid': 777262, 'locationid': 777261, 'variantallele': 'C', 'version': 1, 'sequence_location': {'id': 777261, 'version': 58, 'name': 'c.3257G>A', 'chromosomelocation': 'g.201060815C>T', 'genelocation': 'g.56752G>A', 'proteinlocation': 'p.R1086H', 'genesymbol': 'CACNA1S', 'dbsnpid': 'rs1800559', 'position': 201060815}}]"

In [6]:
df.allele_location_value.iloc[3]

"[{'alleledefinitionid': 777264, 'locationid': 777260, 'variantallele': 'A', 'version': 1, 'sequence_location': {'id': 777260, 'version': 58, 'name': 'c.520C>T', 'chromosomelocation': 'g.201091993G>A', 'genelocation': 'g.25574C>T', 'proteinlocation': 'p.R174W', 'genesymbol': 'CACNA1S', 'dbsnpid': 'rs772226819', 'position': 201091993}}]"

In [7]:
df.allele_location_value.iloc[4]

"[{'alleledefinitionid': 777266, 'locationid': 777261, 'variantallele': 'T', 'version': 1, 'sequence_location': {'id': 777261, 'version': 58, 'name': 'c.3257G>A', 'chromosomelocation': 'g.201060815C>T', 'genelocation': 'g.56752G>A', 'proteinlocation': 'p.R1086H', 'genesymbol': 'CACNA1S', 'dbsnpid': 'rs1800559', 'position': 201060815}}]"

In [8]:
df.allele_location_value.iloc[244]

"[{'alleledefinitionid': 778052, 'locationid': 777856, 'variantallele': 'insTA', 'version': 1, 'sequence_location': {'id': 777856, 'version': 58, 'name': '1888_1889insTA', 'chromosomelocation': 'g.42128903_42128904insTA', 'genelocation': 'g.6907_6908insTA', 'proteinlocation': 'p.S183X', 'genesymbol': 'CYP2D6', 'dbsnpid': None, 'position': 42128903}}]"

In [9]:
data = df.copy()

In [86]:
import pandas as pd
df_1 = pd.read_excel(r'C:/Users/GenepoweRx_Madhu/Downloads/revised_final_new_Allele_definitions_CPIC (1).xlsx')
df_1

,id,version,genesymbol,name,pharmvarid,matchesreferencesequence,structuralvariation,Allele_location_value,alleledefinitionID,locationID,variantallele,Version,ID,Version_sequence_location,Name,chromosomelocation,genelocation,proteinlocation,Genesymbol,dbsnpID,position
0,1508724,38,ABCG2,rs2231142 reference (G),NaN,True,False,"alleledefinitionID: 1508724, locationID: 15087...",1508724,1508723.0,G,1.0,1508723.0,38.0,421C>A,g.88131171G>T,g.105152C>A,Q141K,ABCG2,rs2231142,88131171.0
1,1508726,38,ABCG2,rs2231142 variant (T),NaN,False,False,"alleledefinitionID: 1508726, locationID: 15087...",1508726,1508723.0,T,1.0,1508723.0,38.0,421C>A,g.88131171G>T,g.105152C>A,Q141K,ABCG2,rs2231142,88131171.0
2,777262,57,CACNA1S,Reference,NaN,True,False,"alleledefinitionID: 777262, locationID: 777260...",777262,777260.0,G,1.0,777260.0,58.0,c.520C>T,g.201091993G>A,g.25574C>T,p.R174W,CACNA1S,rs772226819,201091993.0
3,777262,57,CACNA1S,Reference,NaN,True,False,"alleledefinitionID: 777262, locationID: 777261...",777262,777261.0,C,1.0,777261.0,58.0,c.3257G>A,g.201060815C>T,g.56752G>A,p.R1086H,CACNA1S,rs1800559,201060815.0
4,777264,57,CACNA1S,c.520C>T,NaN,False,False,"alleledefinitionID: 777264, locationID: 777260...",777264,777260.0,A,1.0,777260.0,58.0,c.520C>T,g.201091993G>A,g.25574C>T,p.R174W,CACNA1S,rs772226819,201091993.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2029,779504,57,UGT1A1,*80+*37,NaN,False,False,"alleledefinitionID: 779504, locationID: 779484...",779504,779484.0,T,1.0,779484.0,58.0,-364C>T,g.233759924C>T,g.175181C>T,5 Flanking,UGT1A1,rs887829,233759924.0
2030,779504,57,UGT1A1,*80+*37,NaN,False,False,"alleledefinitionID: 779504, locationID: 10005...",779504,1000510.0,TA(9),1.0,1000510.0,49.0,CA(TA)5TAA CA(TA)6TAA CA(TA)7TAA CA(TA)8TAA,g.233760235TA[6]; g.233760235TA[7]; g.23376023...,g.175492TA[6]; g.175492TA[7]; g.175492TA[8]; g...,5 Flanking,UGT1A1,rs3064744,233760235.0
2031,779492,57,UGT1A1,*27,NaN,False,False,"alleledefinitionID: 779492, locationID: 779487...",779492,779487.0,A,1.0,779487.0,58.0,686C>A,g.233760973C>A,g.176230C>A,p.P229Q,UGT1A1,rs35350960,233760973.0
2032,779509,57,VKORC1,rs9923231 variant (T),NaN,False,False,"alleledefinitionID: 779509, locationID: 779506...",779509,779506.0,T,1.0,779506.0,58.0,-1639G>A,g.31096368C>T,g.3588G>A,5 region,VKORC1,rs9923231,31096368.0
2033,779507,57,VKORC1,rs9923231 reference (C),NaN,True,False,"alleledefinitionID: 779507, locationID: 779506...",779507,779506.0,C,1.0,779506.0,58.0,-1639G>A,g.31096368C>T,g.3588G>A,5 region,VKORC1,rs9923231,31096368.0

In [46]:
df_2 = pd.read_csv(r'C:/Users/GenepoweRx_Madhu/Downloads/new_work/clinvar_GRCh38.vcf', sep='\t', comment='#', header=None, low_memory=False)
df_2.columns = ['CHROM', 'POS', 'rsID', 'REF', 'ALT', 'QUAL', 'FILTER', 'INFO']
df_2

,CHROM,POS,rsID,REF,ALT,QUAL,FILTER,INFO
0,1,69134,2205837,A,G,.,.,"ALLELEID=2193183;CLNDISDB=MeSH:D030342,MedGen:..."
1,1,69581,2252161,C,G,.,.,"ALLELEID=2238986;CLNDISDB=MeSH:D030342,MedGen:..."
2,1,69682,2396347,G,A,.,.,"ALLELEID=2386655;CLNDISDB=MeSH:D030342,MedGen:..."
3,1,69769,2288999,T,C,.,.,"ALLELEID=2278803;CLNDISDB=MeSH:D030342,MedGen:..."
4,1,69995,2351346,G,C,.,.,"ALLELEID=2333177;CLNDISDB=MeSH:D030342,MedGen:..."
...,...,...,...,...,...,...,...,...
2248781,NT_187693.1,273806,2219599,G,A,.,.,"ALLELEID=2206917;CLNDISDB=MeSH:D030342,MedGen:..."
2248782,NT_187693.1,273866,2237818,A,C,.,.,"ALLELEID=2232003;CLNDISDB=MeSH:D030342,MedGen:..."
2248783,NT_187693.1,274366,2206666,G,C,.,.,"ALLELEID=2200058;CLNDISDB=MeSH:D030342,MedGen:..."
2248784,NT_187693.1,275068,2241971,T,C,.,.,"ALLELEID=2226217;CLNDISDB=MeSH:D030342,MedGen:..."
2248785,NW_009646201.1,83614,17735,TC,T,.,.,ALLELEID=32774;CLNDISDB=Human_Phenotype_Ontolo...

In [47]:
df_2["Gene_Name"] = df_2["INFO"].str.extract('GENEINFO=(?P<GENEINFO>.+?);')
df_2['Gene'] = df_2['Gene_Name'].apply(lambda x: ','.join([segment.split(':')[0] for segment in x.split('|')]) if pd.notnull(x) else '')
df_2

,CHROM,POS,rsID,REF,ALT,QUAL,FILTER,INFO,Gene_Name,Gene
0,1,69134,2205837,A,G,.,.,"ALLELEID=2193183;CLNDISDB=MeSH:D030342,MedGen:...",OR4F5:79501,OR4F5
1,1,69581,2252161,C,G,.,.,"ALLELEID=2238986;CLNDISDB=MeSH:D030342,MedGen:...",OR4F5:79501,OR4F5
2,1,69682,2396347,G,A,.,.,"ALLELEID=2386655;CLNDISDB=MeSH:D030342,MedGen:...",OR4F5:79501,OR4F5
3,1,69769,2288999,T,C,.,.,"ALLELEID=2278803;CLNDISDB=MeSH:D030342,MedGen:...",OR4F5:79501,OR4F5
4,1,69995,2351346,G,C,.,.,"ALLELEID=2333177;CLNDISDB=MeSH:D030342,MedGen:...",OR4F5:79501,OR4F5
...,...,...,...,...,...,...,...,...,...,...
2248781,NT_187693.1,273806,2219599,G,A,.,.,"ALLELEID=2206917;CLNDISDB=MeSH:D030342,MedGen:...",LILRA3:11026,LILRA3
2248782,NT_187693.1,273866,2237818,A,C,.,.,"ALLELEID=2232003;CLNDISDB=MeSH:D030342,MedGen:...",LILRA3:11026,LILRA3
2248783,NT_187693.1,274366,2206666,G,C,.,.,"ALLELEID=2200058;CLNDISDB=MeSH:D030342,MedGen:...",LILRA3:11026,LILRA3
2248784,NT_187693.1,275068,2241971,T,C,.,.,"ALLELEID=2226217;CLNDISDB=MeSH:D030342,MedGen:...",LILRA3:11026|LOC126057115:126057115,"LILRA3,LOC126057115"
2248785,NW_009646201.1,83614,17735,TC,T,.,.,ALLELEID=32774;CLNDISDB=Human_Phenotype_Ontolo...,ABO:28,ABO

In [48]:
df_gene = pd.read_excel(r'C:/Users/GenepoweRx_Madhu/Desktop/study_match.xlsx')
df_gene

       Gene
0     ABCG2
1   CACNA1S
2      CFTR
3    CYP2B6
4   CYP2C19
5    CYP2C9
6    CYP2D6
7    CYP3A5
8    CYP4F2
9      DPYD
10     G6PD
11    HLA-A
12    HLA-B
13    IFNL3
14  MT-RNR1
15   NUDT15
16     RYR1
17  SLCO1B1
18     TPMT
19   UGT1A1
20   VKORC1

In [49]:
df_2['Gene_Match'] = 'No'
df_2['Matched_Gene'] = ''
    
# Iterate through each gene in vcf['Gene']
for index, genes in df_2['Gene'].iteritems():
    if isinstance(genes, str):
        gene_list = genes.split(',')
        for gene in gene_list:
            if gene in df_gene['Gene'].values:
                df_2.at[index, 'Gene_Match'] = 'Yes'
                df_2.at[index, 'Matched_Gene'] = gene
                break
    
matched = df_2[df_2['Gene_Match'] == 'Yes']

In [50]:
matched

,CHROM,POS,rsID,REF,ALT,QUAL,FILTER,INFO,Gene_Name,Gene,Gene_Match,Matched_Gene
85478,1,97077787,876878,C,T,.,.,AF_TGP=0.00060;ALLELEID=864881;CLNDISDB=MONDO:...,DPYD:1806,DPYD,Yes,DPYD
85479,1,97077823,876879,T,C,.,.,"ALLELEID=864882;CLNDISDB=MONDO:MONDO:0010130,M...",DPYD:1806,DPYD,Yes,DPYD
85480,1,97077914,876880,T,C,.,.,AF_TGP=0.00559;ALLELEID=864883;CLNDISDB=MONDO:...,DPYD:1806,DPYD,Yes,DPYD
85481,1,97077926,876881,T,A,.,.,"ALLELEID=864884;CLNDISDB=MONDO:MONDO:0010130,M...",DPYD:1806,DPYD,Yes,DPYD
85482,1,97077930,298270,G,T,.,.,AF_TGP=0.00319;ALLELEID=283443;CLNDISDB=MONDO:...,DPYD:1806,DPYD,Yes,DPYD
...,...,...,...,...,...,...,...,...,...,...,...,...
2245977,MT,1503,163987,G,A,.,.,ALLELEID=176336;CLNDISDB=MedGen:CN169374;CLNDN...,MT-RNR1:4549,MT-RNR1,Yes,MT-RNR1
2245978,MT,1508,163988,C,T,.,.,ALLELEID=176459;CLNDISDB=MedGen:CN169374;CLNDN...,MT-RNR1:4549,MT-RNR1,Yes,MT-RNR1
2245979,MT,1536,227550,A,G,.,.,ALLELEID=231300;CLNDISDB=MedGen:CN169374;CLNDN...,MT-RNR1:4549,MT-RNR1,Yes,MT-RNR1
2245980,MT,1555,9628,A,G,.,.,"ALLELEID=24667;CLNDISDB=MedGen:CN826980,Orphan...",MT-ND1:4535|MT-RNR1:4549,"MT-ND1,MT-RNR1",Yes,MT-RNR1
2245981,MT,1598,42223,G,A,.,.,ALLELEID=51393;CLNDISDB=MedGen:CN169374|MedGen...,MT-RNR1:4549,MT-RNR1,Yes,MT-RNR1

In [52]:
matched['alleledefinitionID'] = matched['INFO'].str.extract(r'ALLELEID=(?P<ALLELEID>\d+);')
matched

,CHROM,POS,rsID,REF,ALT,QUAL,FILTER,INFO,Gene_Name,Gene,Gene_Match,Matched_Gene,alleledefinitionID
85478,1,97077787,876878,C,T,.,.,AF_TGP=0.00060;ALLELEID=864881;CLNDISDB=MONDO:...,DPYD:1806,DPYD,Yes,DPYD,864881
85479,1,97077823,876879,T,C,.,.,"ALLELEID=864882;CLNDISDB=MONDO:MONDO:0010130,M...",DPYD:1806,DPYD,Yes,DPYD,864882
85480,1,97077914,876880,T,C,.,.,AF_TGP=0.00559;ALLELEID=864883;CLNDISDB=MONDO:...,DPYD:1806,DPYD,Yes,DPYD,864883
85481,1,97077926,876881,T,A,.,.,"ALLELEID=864884;CLNDISDB=MONDO:MONDO:0010130,M...",DPYD:1806,DPYD,Yes,DPYD,864884
85482,1,97077930,298270,G,T,.,.,AF_TGP=0.00319;ALLELEID=283443;CLNDISDB=MONDO:...,DPYD:1806,DPYD,Yes,DPYD,283443
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2245977,MT,1503,163987,G,A,.,.,ALLELEID=176336;CLNDISDB=MedGen:CN169374;CLNDN...,MT-RNR1:4549,MT-RNR1,Yes,MT-RNR1,176336
2245978,MT,1508,163988,C,T,.,.,ALLELEID=176459;CLNDISDB=MedGen:CN169374;CLNDN...,MT-RNR1:4549,MT-RNR1,Yes,MT-RNR1,176459
2245979,MT,1536,227550,A,G,.,.,ALLELEID=231300;CLNDISDB=MedGen:CN169374;CLNDN...,MT-RNR1:4549,MT-RNR1,Yes,MT-RNR1,231300
2245980,MT,1555,9628,A,G,.,.,"ALLELEID=24667;CLNDISDB=MedGen:CN826980,Orphan...",MT-ND1:4535|MT-RNR1:4549,"MT-ND1,MT-RNR1",Yes,MT-RNR1,24667
2245981,MT,1598,42223,G,A,.,.,ALLELEID=51393;CLNDISDB=MedGen:CN169374|MedGen...,MT-RNR1:4549,MT-RNR1,Yes,MT-RNR1,51393

In [71]:
x = matched[['alleledefinitionID']]
x

        alleledefinitionID
85478               864881
85479               864882
85480               864883
85481               864884
85482               283443
...                    ...
2245977             176336
2245978             176459
2245979             231300
2245980              24667
2245981              51393

[13731 rows x 1 columns]

In [73]:
matched.to_excel(r'C:/Users/GenepoweRx_Madhu/Desktop/alleledeID.xlsx', index=False)

In [70]:
x[x['alleledefinitionID'] == 779166]

Empty DataFrame
Columns: [CHROM, POS, rsID, REF, ALT, QUAL, FILTER, INFO, Gene_Name, Gene, Gene_Match, Matched_Gene, alleledefinitionID]
Index: []

In [87]:
df_1 = df_1.rename({'genesymbol':'Matched_Gene'}, axis=1)
df_1

,id,version,Matched_Gene,name,pharmvarid,matchesreferencesequence,structuralvariation,Allele_location_value,alleledefinitionID,locationID,variantallele,Version,ID,Version_sequence_location,Name,chromosomelocation,genelocation,proteinlocation,Genesymbol,dbsnpID,position
0,1508724,38,ABCG2,rs2231142 reference (G),NaN,True,False,"alleledefinitionID: 1508724, locationID: 15087...",1508724,1508723.0,G,1.0,1508723.0,38.0,421C>A,g.88131171G>T,g.105152C>A,Q141K,ABCG2,rs2231142,88131171.0
1,1508726,38,ABCG2,rs2231142 variant (T),NaN,False,False,"alleledefinitionID: 1508726, locationID: 15087...",1508726,1508723.0,T,1.0,1508723.0,38.0,421C>A,g.88131171G>T,g.105152C>A,Q141K,ABCG2,rs2231142,88131171.0
2,777262,57,CACNA1S,Reference,NaN,True,False,"alleledefinitionID: 777262, locationID: 777260...",777262,777260.0,G,1.0,777260.0,58.0,c.520C>T,g.201091993G>A,g.25574C>T,p.R174W,CACNA1S,rs772226819,201091993.0
3,777262,57,CACNA1S,Reference,NaN,True,False,"alleledefinitionID: 777262, locationID: 777261...",777262,777261.0,C,1.0,777261.0,58.0,c.3257G>A,g.201060815C>T,g.56752G>A,p.R1086H,CACNA1S,rs1800559,201060815.0
4,777264,57,CACNA1S,c.520C>T,NaN,False,False,"alleledefinitionID: 777264, locationID: 777260...",777264,777260.0,A,1.0,777260.0,58.0,c.520C>T,g.201091993G>A,g.25574C>T,p.R174W,CACNA1S,rs772226819,201091993.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2029,779504,57,UGT1A1,*80+*37,NaN,False,False,"alleledefinitionID: 779504, locationID: 779484...",779504,779484.0,T,1.0,779484.0,58.0,-364C>T,g.233759924C>T,g.175181C>T,5 Flanking,UGT1A1,rs887829,233759924.0
2030,779504,57,UGT1A1,*80+*37,NaN,False,False,"alleledefinitionID: 779504, locationID: 10005...",779504,1000510.0,TA(9),1.0,1000510.0,49.0,CA(TA)5TAA CA(TA)6TAA CA(TA)7TAA CA(TA)8TAA,g.233760235TA[6]; g.233760235TA[7]; g.23376023...,g.175492TA[6]; g.175492TA[7]; g.175492TA[8]; g...,5 Flanking,UGT1A1,rs3064744,233760235.0
2031,779492,57,UGT1A1,*27,NaN,False,False,"alleledefinitionID: 779492, locationID: 779487...",779492,779487.0,A,1.0,779487.0,58.0,686C>A,g.233760973C>A,g.176230C>A,p.P229Q,UGT1A1,rs35350960,233760973.0
2032,779509,57,VKORC1,rs9923231 variant (T),NaN,False,False,"alleledefinitionID: 779509, locationID: 779506...",779509,779506.0,T,1.0,779506.0,58.0,-1639G>A,g.31096368C>T,g.3588G>A,5 region,VKORC1,rs9923231,31096368.0
2033,779507,57,VKORC1,rs9923231 reference (C),NaN,True,False,"alleledefinitionID: 779507, locationID: 779506...",779507,779506.0,C,1.0,779506.0,58.0,-1639G>A,g.31096368C>T,g.3588G>A,5 region,VKORC1,rs9923231,31096368.0

In [84]:
matched = pd.read_excel(r'C:/Users/GenepoweRx_Madhu/Desktop/alleledeID.xlsx')
matched

,CHROM,POS,rsID,REF,ALT,QUAL,FILTER,INFO,Matched_Gene,alleledefinitionID
0,1,97077787,876878,C,T,.,.,AF_TGP=0.00060;ALLELEID=864881;CLNDISDB=MONDO:...,DPYD,864881
1,1,97077823,876879,T,C,.,.,"ALLELEID=864882;CLNDISDB=MONDO:MONDO:0010130,M...",DPYD,864882
2,1,97077914,876880,T,C,.,.,AF_TGP=0.00559;ALLELEID=864883;CLNDISDB=MONDO:...,DPYD,864883
3,1,97077926,876881,T,A,.,.,"ALLELEID=864884;CLNDISDB=MONDO:MONDO:0010130,M...",DPYD,864884
4,1,97077930,298270,G,T,.,.,AF_TGP=0.00319;ALLELEID=283443;CLNDISDB=MONDO:...,DPYD,283443
...,...,...,...,...,...,...,...,...,...,...
13726,MT,1503,163987,G,A,.,.,ALLELEID=176336;CLNDISDB=MedGen:CN169374;CLNDN...,MT-RNR1,176336
13727,MT,1508,163988,C,T,.,.,ALLELEID=176459;CLNDISDB=MedGen:CN169374;CLNDN...,MT-RNR1,176459
13728,MT,1536,227550,A,G,.,.,ALLELEID=231300;CLNDISDB=MedGen:CN169374;CLNDN...,MT-RNR1,231300
13729,MT,1555,9628,A,G,.,.,"ALLELEID=24667;CLNDISDB=MedGen:CN826980,Orphan...",MT-RNR1,24667
13730,MT,1598,42223,G,A,.,.,ALLELEID=51393;CLNDISDB=MedGen:CN169374|MedGen...,MT-RNR1,51393

In [88]:
# Converting 'alleledefinitionID' column to int in df_1
df_1['alleledefinitionID'] = df_1['alleledefinitionID'].astype(int)

# Converting 'alleledefinitionID' column to int in the 'matched' DataFrame
matched['alleledefinitionID'] = matched['alleledefinitionID'].astype(int)

# Converting 'Matched_Gene' column to str (string) in df_1
df_1['Matched_Gene'] = df_1['Matched_Gene'].astype(str)

# Converting 'Matched_Gene' column to str (string) in the 'matched' DataFrame
matched['Matched_Gene'] = matched['Matched_Gene'].astype(str)

In [89]:
merged_38 = pd.merge(df_1, matched, on=['alleledefinitionID', 'Matched_Gene'], how='left', sort=False)
merged_38

,id,version,Matched_Gene,name,pharmvarid,matchesreferencesequence,structuralvariation,Allele_location_value,alleledefinitionID,locationID,variantallele,Version,ID,Version_sequence_location,Name,chromosomelocation,genelocation,proteinlocation,Genesymbol,dbsnpID,position,CHROM,POS,rsID,REF,ALT,QUAL,FILTER,INFO
0,1508724,38,ABCG2,rs2231142 reference (G),NaN,True,False,"alleledefinitionID: 1508724, locationID: 15087...",1508724,1508723.0,G,1.0,1508723.0,38.0,421C>A,g.88131171G>T,g.105152C>A,Q141K,ABCG2,rs2231142,88131171.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1508726,38,ABCG2,rs2231142 variant (T),NaN,False,False,"alleledefinitionID: 1508726, locationID: 15087...",1508726,1508723.0,T,1.0,1508723.0,38.0,421C>A,g.88131171G>T,g.105152C>A,Q141K,ABCG2,rs2231142,88131171.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,777262,57,CACNA1S,Reference,NaN,True,False,"alleledefinitionID: 777262, locationID: 777260...",777262,777260.0,G,1.0,777260.0,58.0,c.520C>T,g.201091993G>A,g.25574C>T,p.R174W,CACNA1S,rs772226819,201091993.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,777262,57,CACNA1S,Reference,NaN,True,False,"alleledefinitionID: 777262, locationID: 777261...",777262,777261.0,C,1.0,777261.0,58.0,c.3257G>A,g.201060815C>T,g.56752G>A,p.R1086H,CACNA1S,rs1800559,201060815.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,777264,57,CACNA1S,c.520C>T,NaN,False,False,"alleledefinitionID: 777264, locationID: 777260...",777264,777260.0,A,1.0,777260.0,58.0,c.520C>T,g.201091993G>A,g.25574C>T,p.R174W,CACNA1S,rs772226819,201091993.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2029,779504,57,UGT1A1,*80+*37,NaN,False,False,"alleledefinitionID: 779504, locationID: 779484...",779504,779484.0,T,1.0,779484.0,58.0,-364C>T,g.233759924C>T,g.175181C>T,5 Flanking,UGT1A1,rs887829,233759924.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2030,779504,57,UGT1A1,*80+*37,NaN,False,False,"alleledefinitionID: 779504, locationID: 10005...",779504,1000510.0,TA(9),1.0,1000510.0,49.0,CA(TA)5TAA CA(TA)6TAA CA(TA)7TAA CA(TA)8TAA,g.233760235TA[6]; g.233760235TA[7]; g.23376023...,g.175492TA[6]; g.175492TA[7]; g.175492TA[8]; g...,5 Flanking,UGT1A1,rs3064744,233760235.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2031,779492,57,UGT1A1,*27,NaN,False,False,"alleledefinitionID: 779492, locationID: 779487...",779492,779487.0,A,1.0,779487.0,58.0,686C>A,g.233760973C>A,g.176230C>A,p.P229Q,UGT1A1,rs35350960,233760973.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2032,779509,57,VKORC1,rs9923231 variant (T),NaN,False,False,"alleledefinitionID: 779509, locationID: 779506...",779509,779506.0,T,1.0,779506.0,58.0,-1639G>A,g.31096368C>T,g.3588G>A,5 region,VKORC1,rs9923231,31096368.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2033,779507,57,VKORC1,rs9923231 reference (C),NaN,True,False,"alleledefinitionID: 779507, locationID: 779506...",779507,779506.0,C,1.0,779506.0,58.0,-1639G>A,g.31096368C>T,g.3588G>A,5 region,VKORC1,rs9923231,31096368.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [90]:
merged_38.CHROM.isnull().sum()

2034

In [9]:
df_2.INFO.iloc[0]

'ALLELEID=2193183;CLNDISDB=MeSH:D030342,MedGen:C0950123;CLNDN=Inborn_genetic_diseases;CLNHGVS=NC_000001.11:g.69134A>G;CLNREVSTAT=criteria_provided,_single_submitter;CLNSIG=Likely_benign;CLNVC=single_nucleotide_variant;CLNVCSO=SO:0001483;GENEINFO=OR4F5:79501;MC=SO:0001583|missense_variant;ORIGIN=1'

In [21]:
import re
def extract_clnhgvs(info):
    clnhgvs_match = re.search(r'CLNHGVS=NC_000001\.11:(?P<CLNHGVS>[^;]+);', info)
    if clnhgvs_match:
        return clnhgvs_match.group('CLNHGVS')
    return None

df_2['genelocation'] = df_2['INFO'].apply(extract_clnhgvs)
df_2

,CHROM,POS,rsID,REF,ALT,QUAL,FILTER,INFO,genelocation
0,1,69134,2205837,A,G,.,.,"ALLELEID=2193183;CLNDISDB=MeSH:D030342,MedGen:...",g.69134A>G
1,1,69581,2252161,C,G,.,.,"ALLELEID=2238986;CLNDISDB=MeSH:D030342,MedGen:...",g.69581C>G
2,1,69682,2396347,G,A,.,.,"ALLELEID=2386655;CLNDISDB=MeSH:D030342,MedGen:...",g.69682G>A
3,1,69769,2288999,T,C,.,.,"ALLELEID=2278803;CLNDISDB=MeSH:D030342,MedGen:...",g.69769T>C
4,1,69995,2351346,G,C,.,.,"ALLELEID=2333177;CLNDISDB=MeSH:D030342,MedGen:...",g.69995G>C
...,...,...,...,...,...,...,...,...,...
2248781,NT_187693.1,273806,2219599,G,A,.,.,"ALLELEID=2206917;CLNDISDB=MeSH:D030342,MedGen:...",None
2248782,NT_187693.1,273866,2237818,A,C,.,.,"ALLELEID=2232003;CLNDISDB=MeSH:D030342,MedGen:...",None
2248783,NT_187693.1,274366,2206666,G,C,.,.,"ALLELEID=2200058;CLNDISDB=MeSH:D030342,MedGen:...",None
2248784,NT_187693.1,275068,2241971,T,C,.,.,"ALLELEID=2226217;CLNDISDB=MeSH:D030342,MedGen:...",None
2248785,NW_009646201.1,83614,17735,TC,T,.,.,ALLELEID=32774;CLNDISDB=Human_Phenotype_Ontolo...,None

In [37]:
df_new_2 = df_2[['genelocation']]
df_new_2

        genelocation
0         g.69134A>G
1         g.69581C>G
2         g.69682G>A
3         g.69769T>C
4         g.69995G>C
...              ...
2248781         None
2248782         None
2248783         None
2248784         None
2248785         None

[2248786 rows x 1 columns]

In [38]:
df_new_2.isnull().sum()

genelocation    2052446
dtype: int64

In [39]:
2248786-2052446

196340

In [40]:
df_new_2 = df_new_2.dropna()
df_new_2

          genelocation
0           g.69134A>G
1           g.69581C>G
2           g.69682G>A
3           g.69769T>C
4           g.69995G>C
...                ...
196335  g.248917965G>C
196336  g.248917978G>T
196337  g.248918022A>T
196338  g.248918194G>A
196339  g.248918261G>C

[196340 rows x 1 columns]

In [41]:
df_new_2.to_excel(r'C:/Users/GenepoweRx_Madhu/Desktop/data_new.xlsx', index=False)

In [15]:
df_2[df_2['genelocation'] == 'g.150863G>A']

Empty DataFrame
Columns: [CHROM, POS, rsID, REF, ALT, QUAL, FILTER, INFO, genelocation]
Index: []

In [13]:
df_1[df_1['genelocation'] == 'g.69134A>G']

Empty DataFrame
Columns: [id, version, genesymbol, name, pharmvarid, matchesreferencesequence, structuralvariation, Allele_location_value, alleledefinitionID, locationID, variantallele, Version, ID, Version_sequence_location, Name, chromosomelocation, genelocation, proteinlocation, Genesymbol, dbsnpID, position]
Index: []

[0 rows x 21 columns]

In [7]:
df_2.INFO.iloc[2248781]

'ALLELEID=2206917;CLNDISDB=MeSH:D030342,MedGen:C0950123;CLNDN=Inborn_genetic_diseases;CLNREVSTAT=criteria_provided,_single_submitter;CLNSIG=Likely_benign;CLNVC=single_nucleotide_variant;CLNVCSO=SO:0001483;GENEINFO=LILRA3:11026;MC=SO:0001583|missense_variant;ORIGIN=1'

In [11]:
merged_1 = pd.merge(df_1, df_2, on = 'genelocation', how = 'left', sort=False)
merged_1

,id,version,genesymbol,name,pharmvarid,matchesreferencesequence,structuralvariation,Allele_location_value,alleledefinitionID,locationID,...,dbsnpID,position,CHROM,POS,rsID,REF,ALT,QUAL,FILTER,INFO
0,1508724,38,ABCG2,rs2231142 reference (G),NaN,True,False,"alleledefinitionID: 1508724, locationID: 15087...",1508724,1508723.0,...,rs2231142,88131171,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1508726,38,ABCG2,rs2231142 variant (T),NaN,False,False,"alleledefinitionID: 1508726, locationID: 15087...",1508726,1508723.0,...,rs2231142,88131171,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,777262,57,CACNA1S,Reference,NaN,True,False,"alleledefinitionID: 777262, locationID: 777260...",777262,777260.0,...,rs772226819,201091993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,777262,57,CACNA1S,Reference,NaN,True,False,"alleledefinitionID: 777262, locationID: 777261...",777262,777261.0,...,rs1800559,201060815,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,777264,57,CACNA1S,c.520C>T,NaN,False,False,"alleledefinitionID: 777264, locationID: 777260...",777264,777260.0,...,rs772226819,201091993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34893595,779504,57,UGT1A1,*80+*37,NaN,False,False,"alleledefinitionID: 779504, locationID: 779484...",779504,779484.0,...,rs887829,233759924,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34893596,779504,57,UGT1A1,*80+*37,NaN,False,False,"alleledefinitionID: 779504, locationID: 10005...",779504,1000510.0,...,rs3064744,233760235,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34893597,779492,57,UGT1A1,*27,NaN,False,False,"alleledefinitionID: 779492, locationID: 779487...",779492,779487.0,...,rs35350960,233760973,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34893598,779509,57,VKORC1,rs9923231 variant (T),NaN,False,False,"alleledefinitionID: 779509, locationID: 779506...",779509,779506.0,...,rs9923231,31096368,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34893599,779507,57,VKORC1,rs9923231 reference (C),NaN,True,False,"alleledefinitionID: 779507, locationID: 779506...",779507,779506.0,...,rs9923231,31096368,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [133]:
df_2['alleledefinitionID'] = df_2['INFO'].str.extract(r'ALLELEID=(?P<ALLELEID>\d+);')
df_2

,CHROM,POS,rsID,REF,ALT,QUAL,FILTER,INFO,alleledefinitionID
0,1,69134,2205837,A,G,.,.,"ALLELEID=2193183;CLNDISDB=MeSH:D030342,MedGen:...",2193183
1,1,69581,2252161,C,G,.,.,"ALLELEID=2238986;CLNDISDB=MeSH:D030342,MedGen:...",2238986
2,1,69682,2396347,G,A,.,.,"ALLELEID=2386655;CLNDISDB=MeSH:D030342,MedGen:...",2386655
3,1,69769,2288999,T,C,.,.,"ALLELEID=2278803;CLNDISDB=MeSH:D030342,MedGen:...",2278803
4,1,69995,2351346,G,C,.,.,"ALLELEID=2333177;CLNDISDB=MeSH:D030342,MedGen:...",2333177
...,...,...,...,...,...,...,...,...,...
2248781,NT_187693.1,273806,2219599,G,A,.,.,"ALLELEID=2206917;CLNDISDB=MeSH:D030342,MedGen:...",2206917
2248782,NT_187693.1,273866,2237818,A,C,.,.,"ALLELEID=2232003;CLNDISDB=MeSH:D030342,MedGen:...",2232003
2248783,NT_187693.1,274366,2206666,G,C,.,.,"ALLELEID=2200058;CLNDISDB=MeSH:D030342,MedGen:...",2200058
2248784,NT_187693.1,275068,2241971,T,C,.,.,"ALLELEID=2226217;CLNDISDB=MeSH:D030342,MedGen:...",2226217
2248785,NW_009646201.1,83614,17735,TC,T,.,.,ALLELEID=32774;CLNDISDB=Human_Phenotype_Ontolo...,32774

In [134]:
merged_1 = pd.merge(df_1, df_2, on = 'alleledefinitionID', how = 'left', sort=False)
merged_1

,id,version,genesymbol,name,pharmvarid,matchesreferencesequence,structuralvariation,Allele_location_value,alleledefinitionID,locationID,variantallele,Version,ID,Version_sequence_location,Name,chromosomelocation,genelocation,proteinlocation,Genesymbol,dbsnpID,position,CHROM,POS,rsID,REF,ALT,QUAL,FILTER,INFO
0,1508724,38,ABCG2,rs2231142 reference (G),NaN,True,False,"alleledefinitionID: 1508724, locationID: 15087...",1508724,1508723.0,G,1.0,1508723.0,38.0,421C>A,g.88131171G>T,g.105152C>A,Q141K,ABCG2,rs2231142,88131171,7,5987596.0,1518331.0,G,T,.,.,"ALLELEID=1508724;CLNDISDB=MeSH:D003123,MedGen:..."
1,1508726,38,ABCG2,rs2231142 variant (T),NaN,False,False,"alleledefinitionID: 1508726, locationID: 15087...",1508726,1508723.0,T,1.0,1508723.0,38.0,421C>A,g.88131171G>T,g.105152C>A,Q141K,ABCG2,rs2231142,88131171,17,65225294.0,1518333.0,G,A,.,.,ALLELEID=1508726;CLNDISDB=MedGen:CN517202;CLND...
2,777262,57,CACNA1S,Reference,NaN,True,False,"alleledefinitionID: 777262, locationID: 777260...",777262,777260.0,G,1.0,777260.0,58.0,c.520C>T,g.201091993G>A,g.25574C>T,p.R174W,CACNA1S,rs772226819,201091993,2,27225253.0,773480.0,G,T,.,.,AF_ESP=0.00008;AF_EXAC=0.00023;AF_TGP=0.00040;...
3,777262,57,CACNA1S,Reference,NaN,True,False,"alleledefinitionID: 777262, locationID: 777261...",777262,777261.0,C,1.0,777261.0,58.0,c.3257G>A,g.201060815C>T,g.56752G>A,p.R1086H,CACNA1S,rs1800559,201060815,2,27225253.0,773480.0,G,T,.,.,AF_ESP=0.00008;AF_EXAC=0.00023;AF_TGP=0.00040;...
4,777264,57,CACNA1S,c.520C>T,NaN,False,False,"alleledefinitionID: 777264, locationID: 777260...",777264,777260.0,A,1.0,777260.0,58.0,c.520C>T,g.201091993G>A,g.25574C>T,p.R174W,CACNA1S,rs772226819,201091993,3,52370100.0,767216.0,C,T,.,.,AF_EXAC=0.00053;AF_TGP=0.00040;ALLELEID=777264...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2030,779504,57,UGT1A1,*80+*37,NaN,False,False,"alleledefinitionID: 779504, locationID: 779484...",779504,779484.0,T,1.0,779484.0,58.0,-364C>T,g.233759924C>T,g.175181C>T,5 Flanking,UGT1A1,rs887829,233759924,11,117186578.0,789211.0,A,G,.,.,AF_ESP=0.00970;AF_EXAC=0.00883;AF_TGP=0.00539;...
2031,779504,57,UGT1A1,*80+*37,NaN,False,False,"alleledefinitionID: 779504, locationID: 10005...",779504,1000510.0,TA(9),1.0,1000510.0,49.0,CA(TA)5TAA CA(TA)6TAA CA(TA)7TAA CA(TA)8TAA,g.233760235TA[6]; g.233760235TA[7]; g.23376023...,g.175492TA[6]; g.175492TA[7]; g.175492TA[8]; g...,5 Flanking,UGT1A1,rs3064744,233760235,11,117186578.0,789211.0,A,G,.,.,AF_ESP=0.00970;AF_EXAC=0.00883;AF_TGP=0.00539;...
2032,779492,57,UGT1A1,*27,NaN,False,False,"alleledefinitionID: 779492, locationID: 779487...",779492,779487.0,A,1.0,779487.0,58.0,686C>A,g.233760973C>A,g.176230C>A,p.P229Q,UGT1A1,rs35350960,233760973,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2033,779509,57,VKORC1,rs9923231 variant (T),NaN,False,False,"alleledefinitionID: 779509, locationID: 779506...",779509,779506.0,T,1.0,779506.0,58.0,-1639G>A,g.31096368C>T,g.3588G>A,5 region,VKORC1,rs9923231,31096368,10,87513115.0,787367.0,T,TC,.,.,ALLELEID=779509;CLNDISDB=MedGen:CN517202;CLNDN...
2034,779507,57,VKORC1,rs9923231 reference (C),NaN,True,False,"alleledefinitionID: 779507, locationID: 779506...",779507,779506.0,C,1.0,779506.0,58.0,-1639G>A,g.31096368C>T,g.3588G>A,5 region,VKORC1,rs9923231,31096368,11,117363422.0,779720.0,T,C,.,.,AF_EXAC=0.00072;AF_TGP=0.00220;ALLELEID=779507...

In [135]:
merged_1.isnull().sum()

id                             0
version                        0
genesymbol                     0
name                           0
pharmvarid                   806
matchesreferencesequence       0
structuralvariation            0
Allele_location_value          0
alleledefinitionID             0
locationID                    16
variantallele                 16
Version                       16
ID                            16
Version_sequence_location     17
Name                          17
chromosomelocation            17
genelocation                  17
proteinlocation               17
Genesymbol                    18
dbsnpID                       18
position                      18
CHROM                         65
POS                           65
rsID                          65
REF                           65
ALT                           65
QUAL                          65
FILTER                        65
INFO                          65
dtype: int64

In [137]:
df_3 = pd.read_csv(r'C:/Users/GenepoweRx_Madhu/Downloads/new_work/clinvar_GRCh38.vcf', sep='\t', comment='#', header=None, low_memory=False)
df_3.columns = ['CHROM_37', 'POS_37', 'rsID_37', 'REF_37', 'ALT_37', 'QUAL_37', 'FILTER_37', 'INFO_37']
df_3

,CHROM_37,POS_37,rsID_37,REF_37,ALT_37,QUAL_37,FILTER_37,INFO_37
0,1,69134,2205837,A,G,.,.,"ALLELEID=2193183;CLNDISDB=MeSH:D030342,MedGen:..."
1,1,69581,2252161,C,G,.,.,"ALLELEID=2238986;CLNDISDB=MeSH:D030342,MedGen:..."
2,1,69682,2396347,G,A,.,.,"ALLELEID=2386655;CLNDISDB=MeSH:D030342,MedGen:..."
3,1,69769,2288999,T,C,.,.,"ALLELEID=2278803;CLNDISDB=MeSH:D030342,MedGen:..."
4,1,69995,2351346,G,C,.,.,"ALLELEID=2333177;CLNDISDB=MeSH:D030342,MedGen:..."
...,...,...,...,...,...,...,...,...
2248781,NT_187693.1,273806,2219599,G,A,.,.,"ALLELEID=2206917;CLNDISDB=MeSH:D030342,MedGen:..."
2248782,NT_187693.1,273866,2237818,A,C,.,.,"ALLELEID=2232003;CLNDISDB=MeSH:D030342,MedGen:..."
2248783,NT_187693.1,274366,2206666,G,C,.,.,"ALLELEID=2200058;CLNDISDB=MeSH:D030342,MedGen:..."
2248784,NT_187693.1,275068,2241971,T,C,.,.,"ALLELEID=2226217;CLNDISDB=MeSH:D030342,MedGen:..."
2248785,NW_009646201.1,83614,17735,TC,T,.,.,ALLELEID=32774;CLNDISDB=Human_Phenotype_Ontolo...

In [138]:
df_3['alleledefinitionID'] = df_3['INFO_37'].str.extract(r'ALLELEID=(?P<ALLELEID>\d+);')
df_3

,CHROM_37,POS_37,rsID_37,REF_37,ALT_37,QUAL_37,FILTER_37,INFO_37,alleledefinitionID
0,1,69134,2205837,A,G,.,.,"ALLELEID=2193183;CLNDISDB=MeSH:D030342,MedGen:...",2193183
1,1,69581,2252161,C,G,.,.,"ALLELEID=2238986;CLNDISDB=MeSH:D030342,MedGen:...",2238986
2,1,69682,2396347,G,A,.,.,"ALLELEID=2386655;CLNDISDB=MeSH:D030342,MedGen:...",2386655
3,1,69769,2288999,T,C,.,.,"ALLELEID=2278803;CLNDISDB=MeSH:D030342,MedGen:...",2278803
4,1,69995,2351346,G,C,.,.,"ALLELEID=2333177;CLNDISDB=MeSH:D030342,MedGen:...",2333177
...,...,...,...,...,...,...,...,...,...
2248781,NT_187693.1,273806,2219599,G,A,.,.,"ALLELEID=2206917;CLNDISDB=MeSH:D030342,MedGen:...",2206917
2248782,NT_187693.1,273866,2237818,A,C,.,.,"ALLELEID=2232003;CLNDISDB=MeSH:D030342,MedGen:...",2232003
2248783,NT_187693.1,274366,2206666,G,C,.,.,"ALLELEID=2200058;CLNDISDB=MeSH:D030342,MedGen:...",2200058
2248784,NT_187693.1,275068,2241971,T,C,.,.,"ALLELEID=2226217;CLNDISDB=MeSH:D030342,MedGen:...",2226217
2248785,NW_009646201.1,83614,17735,TC,T,.,.,ALLELEID=32774;CLNDISDB=Human_Phenotype_Ontolo...,32774

In [139]:
merged_2 = pd.merge(merged_1, df_3, on = 'alleledefinitionID', how = 'left', sort=False)
merged_2

,id,version,genesymbol,name,pharmvarid,matchesreferencesequence,structuralvariation,Allele_location_value,alleledefinitionID,locationID,variantallele,Version,ID,Version_sequence_location,Name,chromosomelocation,genelocation,proteinlocation,Genesymbol,dbsnpID,position,CHROM,POS,rsID,REF,ALT,QUAL,FILTER,INFO,CHROM_37,POS_37,rsID_37,REF_37,ALT_37,QUAL_37,FILTER_37,INFO_37
0,1508724,38,ABCG2,rs2231142 reference (G),NaN,True,False,"alleledefinitionID: 1508724, locationID: 15087...",1508724,1508723.0,G,1.0,1508723.0,38.0,421C>A,g.88131171G>T,g.105152C>A,Q141K,ABCG2,rs2231142,88131171,7,5987596.0,1518331.0,G,T,.,.,"ALLELEID=1508724;CLNDISDB=MeSH:D003123,MedGen:...",7,5987596.0,1518331.0,G,T,.,.,"ALLELEID=1508724;CLNDISDB=MeSH:D003123,MedGen:..."
1,1508726,38,ABCG2,rs2231142 variant (T),NaN,False,False,"alleledefinitionID: 1508726, locationID: 15087...",1508726,1508723.0,T,1.0,1508723.0,38.0,421C>A,g.88131171G>T,g.105152C>A,Q141K,ABCG2,rs2231142,88131171,17,65225294.0,1518333.0,G,A,.,.,ALLELEID=1508726;CLNDISDB=MedGen:CN517202;CLND...,17,65225294.0,1518333.0,G,A,.,.,ALLELEID=1508726;CLNDISDB=MedGen:CN517202;CLND...
2,777262,57,CACNA1S,Reference,NaN,True,False,"alleledefinitionID: 777262, locationID: 777260...",777262,777260.0,G,1.0,777260.0,58.0,c.520C>T,g.201091993G>A,g.25574C>T,p.R174W,CACNA1S,rs772226819,201091993,2,27225253.0,773480.0,G,T,.,.,AF_ESP=0.00008;AF_EXAC=0.00023;AF_TGP=0.00040;...,2,27225253.0,773480.0,G,T,.,.,AF_ESP=0.00008;AF_EXAC=0.00023;AF_TGP=0.00040;...
3,777262,57,CACNA1S,Reference,NaN,True,False,"alleledefinitionID: 777262, locationID: 777261...",777262,777261.0,C,1.0,777261.0,58.0,c.3257G>A,g.201060815C>T,g.56752G>A,p.R1086H,CACNA1S,rs1800559,201060815,2,27225253.0,773480.0,G,T,.,.,AF_ESP=0.00008;AF_EXAC=0.00023;AF_TGP=0.00040;...,2,27225253.0,773480.0,G,T,.,.,AF_ESP=0.00008;AF_EXAC=0.00023;AF_TGP=0.00040;...
4,777264,57,CACNA1S,c.520C>T,NaN,False,False,"alleledefinitionID: 777264, locationID: 777260...",777264,777260.0,A,1.0,777260.0,58.0,c.520C>T,g.201091993G>A,g.25574C>T,p.R174W,CACNA1S,rs772226819,201091993,3,52370100.0,767216.0,C,T,.,.,AF_EXAC=0.00053;AF_TGP=0.00040;ALLELEID=777264...,3,52370100.0,767216.0,C,T,.,.,AF_EXAC=0.00053;AF_TGP=0.00040;ALLELEID=777264...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2030,779504,57,UGT1A1,*80+*37,NaN,False,False,"alleledefinitionID: 779504, locationID: 779484...",779504,779484.0,T,1.0,779484.0,58.0,-364C>T,g.233759924C>T,g.175181C>T,5 Flanking,UGT1A1,rs887829,233759924,11,117186578.0,789211.0,A,G,.,.,AF_ESP=0.00970;AF_EXAC=0.00883;AF_TGP=0.00539;...,11,117186578.0,789211.0,A,G,.,.,AF_ESP=0.00970;AF_EXAC=0.00883;AF_TGP=0.00539;...
2031,779504,57,UGT1A1,*80+*37,NaN,False,False,"alleledefinitionID: 779504, locationID: 10005...",779504,1000510.0,TA(9),1.0,1000510.0,49.0,CA(TA)5TAA CA(TA)6TAA CA(TA)7TAA CA(TA)8TAA,g.233760235TA[6]; g.233760235TA[7]; g.23376023...,g.175492TA[6]; g.175492TA[7]; g.175492TA[8]; g...,5 Flanking,UGT1A1,rs3064744,233760235,11,117186578.0,789211.0,A,G,.,.,AF_ESP=0.00970;AF_EXAC=0.00883;AF_TGP=0.00539;...,11,117186578.0,789211.0,A,G,.,.,AF_ESP=0.00970;AF_EXAC=0.00883;AF_TGP=0.00539;...
2032,779492,57,UGT1A1,*27,NaN,False,False,"alleledefinitionID: 779492, locationID: 779487...",779492,779487.0,A,1.0,779487.0,58.0,686C>A,g.233760973C>A,g.176230C>A,p.P229Q,UGT1A1,rs35350960,233760973,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2033,779509,57,VKORC1,rs9923231 variant (T),NaN,False,False,"alleledefinitionID: 779509, locationID: 779506...",779509,779506.0,T,1.0,779506.0,58.0,-1639G>A,g.31096368C>T,g.3588G>A,5 region,VKORC1,rs9923231,31096368,10,87513115.0,787367.0,T,TC,.,.,ALLELEID=779509;CLNDISDB=MedGen:CN517202;CLNDN...,10,87513115.0,787367.0,T,TC,.,.,ALLELEID=779509;CLNDISDB=MedGen:CN517202;CLNDN...
2034,779507,57,VKORC1,rs9923231 reference (C),NaN,True,False,"alleledefinitionID: 779507, locationID: 779506...",779507,779506.0,C,1.0,779506.0,58.0,-1639G>A,g.31096368C>T,g.3588G>A,5 region,VKORC1,rs9923231,31096368,11,117363422.0,779720.0,T,C,.,.,AF_EXAC=0.00072;AF_TGP=0.00220;ALLELEID=779507...,11,117363422.0,779720.0,T,C,.,.,AF_EXAC=0.00072;AF_TGP=0.00220;ALLELEID=779507...

In [140]:
merged_2.CHROM_37.isnull().sum()

65

In [142]:
merged_2.to_excel(r'C:/Users/GenepoweRx_Madhu/Downloads/new_work/data_final_38_37.xlsx', index=False)